services:
  albyhub:
    image: ghcr.io/getalby/hub:latest
    container_name: albyhub
    env_file: .env
    volumes:
      - ../albyhub/albyhub-data:/data
    expose:             # internal only - no public port needed
      - "8080"
    restart: unless-stopped
    networks:
      - web

  website:
    image: f418-website
    container_name: website
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - web

  boltcipherverifier:
    build: ./boltcipherverifier
    container_name: boltcipherverifier
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - albyhub
      - website
      - boltcipherverifier
    environment:
      - ACME_AGREE=true
      - EMAIL=${CADDY_ACME_EMAIL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "host.containers.internal:host-gateway"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

