services:
  albyhub:
    image: ghcr.io/getalby/hub:latest
    container_name: albyhub
    env_file: .env
    volumes:
      - ./albyhub-data:/data
    expose:             # internal only - no public port needed
      - "8080"
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - albyhub
    environment:
      - ACME_AGREE=true
      - EMAIL=${CADDY_ACME_EMAIL}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

